version: "3"

services:
  pgadmin4-docker-extension:
    image: ${DESKTOP_PLUGIN_IMAGE}
  pgadmin:
    image: dpage/pgadmin4:6.19
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - "PGADMIN_DEFAULT_EMAIL=user@domain.com"
      - "PGADMIN_DEFAULT_PASSWORD=SuperSecret"
      - "PGADMIN_DISABLE_POSTFIX=True"
      - "PGADMIN_LISTEN_PORT=9080"
      - "PGADMIN_CONFIG_LOGIN_BANNER='Authorised users only!'"
      - "PGADMIN_CONFIG_SERVER_MODE=False"
      - "PGADMIN_CONFIG_X_FRAME_OPTIONS=''"
      - 'PGADMIN_CONFIG_CONTENT_SECURITY_POLICY="default-src http: data: ''unsafe-inline'' ''unsafe-eval'';"'
      - "PGADMIN_CONFIG_STRICT_TRANSPORT_SECURITY_ENABLED=True"
      - "PGADMIN_CONFIG_SESSION_COOKIE_SAMESITE='None'"
      - "PGADMIN_CONFIG_SESSION_COOKIE_SECURE=True"
      - "GUNICORN_ACCESS_LOGFILE=/dev/null"
    ports:
      - 9080:9080
volumes:
  pgadmin_data:
